### ISSUE TITLE
API: Adapt Endpoint "Drivers/TourPlans"

### ISSUE THREAD

**Issue by CuzImLloyd** [BWSuDrive/uDrive.Backend#33]
Für https://bwsudrive.github.io/uDrive.Backend/articles/apicallguide.html#post-driverstourplans wäre es meiner Meinung nach gut, noch ein Feld "message" (siehe Beispiel Login https://bwsudrive.github.io/uDrive.Backend/articles/apicallguide.html#login) zu haben, um eventuelle Meldung dem Benutzer anzuzeigen.

@benwirren Findest du das ist sinnvoll?

**Comment by benwirren** [comment]
Hm, ja, können wir einbauen, aber das sind Daten, die während der Tour, in der Datenbank gespeichert werden

**Comment by CuzImLloyd** [comment]
Ah ok, verstehe. 

Dann hätte ich noch eine Frage bzgl der App bzw einer Funktion:


![Image](https://github.com/BWSuDrive/uDrive.Backend/assets/83364953/cd795b84-32b9-4b7c-9282-3296b49d640c)


Unter dem Punkt "Start" werden alle verfügbaren Fahrer im Umkreis von ~5km aufgelistet. Dafür benötigen wir meines Wissens 
nach noch einen Endpoint, oder? Da schicken wir dem Backend die Koordinaten und das filtert dann alle in Frage kommenden
Fahrer raus.

"Nachrichten" wird leer bleiben, da das zu kompliziert ist und zeitlich nicht mehr zu realisieren ist.

Bei "Meine Fahrt" sieht man dann seine nächste Fahrt, sofern man eine eingetragen hat, oder? ( @n-loewen @Skilecto )
Wenn das der Fall sein sollte, gibt es einen Endpoint bei dem wir für einen Fahrer X die nächste Fahrt bekommen?
Die Fahrt kann zwar beim eintragen gespeichert werden, geht aber beim schließen der App verloren (daher der Endpoint).

Im "Fahrtenplaner" kann man seine nächste Fahrt planen. Dafür haben wir ja schon einen Endpoint (/Drivers/TourPlans) und die Klassen dafür habe ich vorbereitet (siehe [hier](https://github.com/BWSuDrive/uDrive.Frontend/tree/prepareAPI))

**Comment by benwirren** [comment]
Ich habe den Issue mal aufgedröselt in #35 , #34 & #36

**Comment by benwirren** [comment]
solved with the linked issues
